from collections import deque
numbers = deque([1, 2, 3, 4, 5], maxlen=20)  # maxlen limits the size of the deque
print(numbers)  # Output: deque([1, 2, 3, 4, 5], maxlen=20)
print(numbers.append(6))  # Output: None (append modifies the deque in place)
print(numbers)  # Output: deque([1, 2, 3, 4, 5, 6], maxlen=20)
print(numbers.appendleft(0))  # Output: None (appendleft modifies the deque in place)
print(numbers)  # Output: deque([0, 1, 2, 3, 4, 5, 6], maxlen=20)
print(numbers.pop())  # Output: 6 (removes and returns the rightmost item)
print(numbers)  # Output: deque([0, 1, 2, 3, 4, 5], maxlen=20)
print(numbers.popleft())  # Output: 0 (removes and returns the leftmost item)
print(numbers)  # Output: deque([1, 2, 3, 4, 5], maxlen=20) 
print(numbers.extend([7, 8, 9]))  # Output: None (extend modifies the deque in place)
print(numbers)  # Output: deque([1, 2, 3, 4, 5, 7, 8, 9], maxlen=20)
print(numbers.extendleft([-1,-2,-3 ]))  # Output: None (extendleft modifies the deque in place)
print(numbers)  # Output: deque([-3, -2, -1, 1, 2, 3, 4, 5, 7, 8, 9], maxlen=20)
print(numbers.insert(3,0))
print(numbers)  # Output: deque([-3, -2, -1, 0, 1, 2, 3, 4, 5, 7, 8, 9], maxlen=20)
print(numbers.remove(0))  # Output: None (remove modifies the deque in place)
print(numbers)  # Output: deque([-3, -2, -1, 1, 2, 3, 4, 5, 7, 8, 9], maxlen=20)
print(numbers.count(3))  # Output: 1 (counts the occurrences of 3 in the deque)
print(numbers.reverse())  # Output: None (reverse modifies the deque in place)      
print(numbers)  # Output: deque([9, 8, 7, 5, 4, 3, 2, 1, -1, -2, -3], maxlen=20)    
print(numbers.rotate(2))  # Output: None (rotate modifies the deque in place   )
print(numbers)  # Output: deque([-2, -3, 9, 8, 7, 5, 4, 3, 2, 1, -1], maxlen=20)
print(numbers.copy())
print(numbers)  # Output: deque([-2, -3, 9, 8, 7, 5, 4, 3, 2, 1, -1], maxlen=20)    
print(numbers.clear())  # Output: None (clear modifies the deque in place)
print(numbers)  # Output: deque([], maxlen=20)
